### ISSUE TITLE
/etc/yum/yum-cron-hourly.conf should also be managed on CentOS

### ISSUE THREAD

**Issue by siebrand** [treydock/puppet-yum_cron#10]
It appears that the configuration for the hourly yum-cron run isn't managed by this module, at least not on CentOS 7.

Files involved:
- /etc/yum/yum-cron-hourly.conf
- /etc/cron.hourly/0yum-hourly.cron (contents: ```exec /usr/sbin/yum-cron /etc/yum/yum-cron-hourly.conf```)

This is my hiera configuration:

```
yum_cron::apply_updates: true
yum_cron::extra_configs:
  'email/email_from':
    value: "no-reply@example.com"
```

This is the diff between the two configuration files with the above configuration:

```
diff /etc/yum/yum-cron.conf /etc/yum/yum-cron-hourly.conf
11,13c11,12
< # Whether a message should be emitted when updates are available,
< # were downloaded, or applied.
< update_messages = yes
---
> # Whether a message should emitted when updates are available.
> update_messages = no
15,16c14,16
< # Whether updates should be downloaded when they are available.
< download_updates = yes
---
> # Whether updates should be downloaded when they are available. Note
> # that updates_messages must also be yes for updates to be downloaded.
> download_updates = no
19,20c19,21
< # that download_updates must also be yes for the update to be applied.
< apply_updates = yes
---
> # that both update_messages and download_updates must also be yes for
> # the update to be applied
> apply_updates = no
27,28c28
< # 6*60 = 360
< random_sleep = 360
---
> random_sleep = 15
34c34
< system_name = some_hostname
---
> system_name = None
51c51
< email_from = no-reply@example.com
---
> email_from = root
61d60
< # NOTE: This only works when group_command != objects, which is now the default
```

I don't know if yum-cron behaves the same on all supported platforms, but there should probably be separate settings for configuration of this file.

**Comment by hdep** [comment]
Hi, 

looking at the configuration on my system there is two file : 
/etc/yum/yum-cron-hourly.conf 
and the cron job : /etc/cron.hourly/0yum-hourly.cron

I think it should be great to be able to disable this.

**Comment by treydock** [comment]
Added `extra_hourly_configs` hash to v5.0.0.
