### ISSUE TITLE
Can't install from puppet-forge : dependency problem 

### ISSUE THREAD

**Issue by jehane** [treydock/puppet-yum_cron#18]
Hi, 
I want to install the module from the forge but I got a dependency problem. 

yum_cron requires puppetlabs/stdlib in a version inferior to 5 when the current version is 5.2 
herculesteam/augeasproviders_shellvar will be an issue too (current version 3.0.0 when yum_cron requires a version <3.0) 

Is it possible to update the requirement ?

**Comment by treydock** [comment]
@jehane This was fixed in master some time ago but not released.  I've added 4.1.0 to the forge that should resolve your issue.
