### ISSUE TITLE
Add days_of_week support for rhel 7

### ISSUE THREAD

**Issue by hdep** [treydock/puppet-yum_cron#22]
Hi,

days_of_week is not supported by yum-cron on rhel/centos 7.
But we could add this feature by managing /etc/cron.daily/0yum-daily.cron file with a template and add a bash test using date '+%u' in order to get the week of the day configured.

What do you think ? 

Can I provide a fix ? 

Best regards

**Comment by treydock** [comment]
I think this would be good for profile class or site specific change. Ideally this module would stick to what's provided by the operating system.
