### ISSUE TITLE
Exclude option

### ISSUE THREAD

**Issue by jsmelser** [treydock/puppet-yum_cron#31]
Is it possible to add an exclude option? some of our servers have software we only want to update manually and we use the exclude option to do this.

**Comment by treydock** [comment]
Where is the exclude option set? I am looking at `/etc/yum/yum-cron.conf` on CentOS 7 and don't see an exclude option.

**Comment by hseagle2015** [comment]
Hi @treydock,

I'm interested in the same feature. By default, exclude option is not present in the yum-cron configuration file, but it can be defined.

For  EL7:

```
# this goes in [base] configuration section
exclude = package1 package2 package3
```


And since this module supports EL6...

```
# packages can be excluded by passing yum parameters.
# This means that "-x" switch must precede each package.
YUM_PARAMETER="-x package1 -x package2 -x package3"
```
