### ISSUE TITLE
Add defaults for RHEL 9(+)

### ISSUE THREAD

**Issue by maggu** [treydock/puppet-yum_cron#41]
We're currently testing RHEL 9 beta in our environment, and yum_cron breaks since defaults (yum_cron::package_name, yum_cron::service_name and yum_cron::config_path) are missing. We've tested adding 9.yaml, and then everything works fine.

So it seems to me it's getting time to add defaults for RHEL 9 as well. They are the same as for RHEL 8 (and will probably be the same for RHEL 10), so maybe add them in the manifest and override in Hiera for RHEL 7 only?

**Comment by Pigueiras** [comment]
Does it work fine for rhel9? I guess it also need to have these defaults no?

https://github.com/treydock/puppet-yum_cron/blob/master/manifests/config.pp#L8

**Comment by Jayden-Lind** [comment]
This worked for me, https://github.com/treydock/puppet-yum_cron/pull/42, but I also don't use any of those other parameters.
