### ISSUE TITLE
download_updates logic is different between EL6 and EL7

### ISSUE THREAD

**Issue by HT43-bqxFqB** [treydock/puppet-yum_cron#7]
In EL6 systems yum-cron uses the following logic:

> # Don't install, just check and download (valid: yes|no)
> # Implies CHECK_ONLY=yes (gotta check first to see what to download)
> DOWNLOAD_ONLY=no

In EL7 based system it's:

> # Whether updates should be downloaded when they are available.
> download_updates = no
> 
> # Whether updates should be applied when they are available.  Note
> # that download_updates must also be yes for the update to be applied.
> apply_updates = yes

So to have automatic updates enabled you have to make DOWNLOAD_ONLY=no in EL6 systems and 
download_updates = yes in EL7 systems. Either the module should use different variables for this or the internal logic should be changed to represent that key difference. Both can't be managed by $download_updates currently!

**Comment by treydock** [comment]
@HT43-bqxFqB Ah I see the issue.  The changes between EL6 and EL7 are a huge pain to automate and I personally don't have any systems with automatic updates enabled.   I'll see if I can work out a way to make automatic updates possible.

**Comment by treydock** [comment]
@HT43-bqxFqB I have pushed a change to 3.x branch that should fix this issue.  I'll release 3.0.0 once I've had a chance to test this change on my systems which don't use automatic updates.

**Comment by siebrand** [comment]
What's blocking the release of this feature?

**Comment by treydock** [comment]
@siebrand Released 3.0.0
