### ISSUE TITLE
emit_via variable on CentOS7

### ISSUE THREAD

**Issue by tbellembois** [treydock/puppet-yum_cron#8]
Hello,

I do not receive any mail on CentOS7 (CentOS Linux release 7.2.1511 (Core)).
Apparently this is due to the default value of `emit_via = stdio` that is not changed by puppet-yum_cron. Changing it to `emit_via = stdio,email` solves the problem.

Moreover I can send mails with:
 `echo "Subject:test" | mail thomas.bellembois@clermont.in2p3.fr`

Have I made any mistake in my configuration ? Any way to fix this ?

Thanks

**Comment by Txalamar** [comment]
Hi,

I'm on the same situation. `emit_via = stdio` by default on CentOS7. Any updates on this issue?

Thanks!!

**Comment by siebrand** [comment]
You can update your configuration as follows to add email to emir_via:

```
class { 'yum_cron':
  extra_configs => {
    'emitters/emit_via' => { 'value' => 'stdio,email' }
  }
}
```

Or using hiera:

```
yum_cron::extra_configs:
  'emitters/emit_via':
    value: 'stdio,email'
```

I'm using the default "stdio" setting on CentOS 7, and I'm not having any issues with getting the status emails sent. I do have a sender configured that is from a valid domain (email/email_from).

**Comment by treydock** [comment]
@siebrand Thanks for the examples.
