### ISSUE TITLE
Yum installed version is older than latest when installing yum-cron

### ISSUE THREAD

**Issue by cdenneen** [treydock/puppet-yum_cron#9]
```
  Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install yum-cron' returned 1: Transaction check error:
    file /etc/yum/yum-cron-hourly.conf from install of yum-cron-3.4.3-150.el7.centos.noarch conflicts with file from package yum-3.4.3-132.el7.centos.0.1.noarch
```
To fix this yum has to be upgraded first and when yum-cron installs it will match version.
Any idea how to "upgrade" yum if necessary?

**Comment by x-yuri** [comment]
Not sure if it answers your question, but `yum install yum`?

**Comment by cdenneen** [comment]
Unless you are suggesting for this module to manage yum I'm not sure what
you are referring to. If the install of yum is older than current version
of yum_cron and it doesn't match it will fail because of older yum
